import {
  MdCalculate,
  MdCreditCard,
  MdFingerprint,
  MdGavel,
  MdGraphicEq,
  MdLocalHospital,
  MdPrecisionManufacturing,
  MdRestaurant,
  MdFitnessCenter,
  MdSchool,
} from "react-icons/md";
import smartSchoolLogo from "../public/smartschoolai.png";

export const PRODUCT_BALLS = [
  {
    id: "books",
    name: "SmartBooks",
    image: "/smartbooksai.png",
    color: "#5040a0",
    inset: 1,
    ball: "radial-gradient(circle at 30% 22%, #a99bea 0%, #5040a0 48%, #24176c 100%)",
    soft: "#f1eefb",
    texture: "grid",
    textureSize: 20,
    Icon: MdCalculate,
    description: "Accounting, GST, inventory, payroll, and financial intelligence.",
    features: ["GST billing", "Inventory", "Bank reconciliation", "AI accounting"],
  },
  {
    id: "school",
    name: "SmartSchool",
    image: smartSchoolLogo,
    color: "#0860d0",
    inset: 6,
    ball: "#0860d0",
    soft: "#eaf2fd",
    texture: "lines",
    textureSize: 15,
    Icon: MdSchool,
    logoFilter: "brightness(0) invert(1)",
    description: "A complete operating system for modern schools.",
    features: ["Students & fees", "Attendance & exams", "Transport & library", "AI analytics"],
  },
  {
    id: "attendance",
    name: "SmartAttendance",
    image: "/smartattendanceaiicon.png",
    color: "#40a040",
    inset: 1,
    ball: "radial-gradient(circle at 30% 22%, #9bdc91 0%, #40a040 48%, #1d6123 100%)",
    soft: "#edf9ec",
    texture: "dots",
    textureSize: 16,
    Icon: MdFingerprint,
    description: "Identity-led workforce attendance built for real operations.",
    features: ["Face attendance", "Geo tracking", "Shifts & leave", "Payroll integration"],
  },
  {
    id: "lift",
    name: "SmartLift",
    image: "/smartliftaiicon.png",
    color: "#5b6675",
    inset: 9,
    ball: "radial-gradient(circle at 30% 22%, #ffffff 0%, #f4f7fa 55%, #b8c2cd 100%)",
    soft: "#f0f2f5",
    texture: "grid",
    textureSize: 30,
    Icon: MdPrecisionManufacturing,
    description: "Research-led robotics, automation, IoT, and intelligent machines.",
    features: ["Robotics", "Industrial automation", "IoT systems", "Machine vision"],
  },
  {
    id: "gym",
    name: "SmartGym",
    image: "/smartgymaiicon.png",
    color: "#68a92d",
    inset: 1,
    ball: "#68a92d",
    soft: "#f0f8e8",
    texture: "stripes",
    textureSize: 14,
    Icon: MdFitnessCenter,
    blend: true,
    description: "Membership, trainers, workouts, billing, and retention in one fitness OS.",
    features: ["Memberships", "Trainer schedules", "Workout plans", "Smart renewals"],
  },
  {
    id: "hospital",
    name: "SmartHospital",
    image: "/smarthospitalaiicon.png",
    color: "#087f80",
    inset: 6,
    ball: "#087f80",
    soft: "#e7f6f6",
    texture: "dots",
    textureSize: 20,
    Icon: MdLocalHospital,
    logoFilter: "brightness(0) invert(1)",
    description: "Connected patient, appointment, billing, pharmacy, and clinical workflows.",
    features: ["Patient records", "Appointments", "Pharmacy & lab", "Hospital analytics"],
  },
  {
    id: "lawyer",
    name: "SmartLawyer",
    image: "/smartlawyeraiicon.png",
    color: "#102c4f",
    inset: 1,
    ball: "#dcecf8",
    soft: "#eaf0f6",
    texture: "columns",
    textureSize: 22,
    Icon: MdGavel,
    blend: true,
    description: "Cases, clients, documents, hearings, and legal intelligence together.",
    features: ["Case management", "Court diary", "Legal documents", "AI legal assistant"],
  },
  {
    id: "payments",
    name: "SmartPayments",
    image: "/smartpaymentsaiicon.png",
    color: "#6f16d9",
    inset: 6,
    ball: "#6f16d9",
    soft: "#f2eafc",
    texture: "dots",
    textureSize: 26,
    Icon: MdCreditCard,
    logoFilter: "brightness(0) invert(1)",
    description: "Secure payment collection, reconciliation, reminders, and insights.",
    features: ["Payment links", "Auto reminders", "Reconciliation", "Payment analytics"],
  },
  {
    id: "restaurant",
    name: "SmartRestaurant",
    image: "/smartrestaurantaiicon.png",
    color: "#102c4f",
    inset: 1,
    ball: "#e7eef5",
    soft: "#eef2f6",
    texture: "rings",
    textureSize: 70,
    Icon: MdRestaurant,
    blend: true,
    description: "Orders, tables, kitchen, inventory, delivery, and guest experience.",
    features: ["POS & orders", "Table management", "Kitchen flow", "Guest insights"],
  },
  {
    id: "voice",
    name: "SmartVoice",
    image: "/smartvoiceaiicon.png",
    color: "#527d1f",
    inset: 6,
    ball: "#527d1f",
    soft: "#eff7e6",
    texture: "waves",
    Icon: MdGraphicEq,
    logoFilter: "brightness(0) invert(1)",
    description: "Conversational voice AI for calls, support, follow-ups, and bookings.",
    features: ["AI calling", "Call routing", "Lead follow-up", "Voice analytics"],
  },
];
